CREATE TABLE datatypes
(
   col1 "char", 
   col2 "char"[], 
   col3 abstime, 
   col4 abstime[], 
   col5 aclitem, 
   col6 aclitem[], 
   col7 bigint, 
   col8 bigint[], 
   col9 bigserial, 
   col10 bit, 
   col11 bit varying, 
   col12 character varying[], 
   col13 bit[], 
   col14 boolean, 
   col15 boolean[], 
   col16 bytea, 
   col17 bytea[], 
   col18 character, 
   col19 character varying, 
   col20 character varying[], 
   col21 character[], 
   col22 cid, 
   col23 cid[], 
   col24 cidr, 
   col25 cidr[], 
   col26 circle, 
   col27 circle[], 
   col29 date, 
   col30 date[], 
   col31 double precision, 
   col32 double precision[], 
   col33 gtsvector, 
   col34 gtsvector[], 
   col35 inet, 
   col36 inet[], 
   col37 int2vector, 
   col38 int2vector[], 
   col39 integer, 
   col40 integer[], 
   col41 interval, 
   col42 interval[], 
   col43 line, 
   col44 line[], 
   col45 lseg, 
   col46 lseg[], 
   col47 macaddr, 
   col48 macaddr[], 
   col49 money, 
   col50 money[], 
   col51 name, 
   col52 name[], 
   col53 numeric, 
   col54 numeric[], 
   col55 oid, 
   col56 oid[], 
   col57 oidvector, 
   col58 oidvector[], 
   col59 path, 
   col60 path[], 
   col61 pg_node_tree, 
   col62 point, 
   col63 point[], 
   col64 polygon, 
   col65 polygon[], 
   col66 real, 
   col67 real[], 
   col68 refcursor, 
   col69 refcursor[], 
   col70 regclass, 
   col71 regclass[], 
   col72 regconfig, 
   col73 regconfig[], 
   col74 regdictionary, 
   col75 regdictionary[], 
   col76 regoper, 
   col77 regoper[], 
   col78 regoperator, 
   col79 regoperator[], 
   col80 regproc, 
   col81 regproc[], 
   col82 regprocedure, 
   col83 regprocedure[], 
   col84 regtype, 
   col85 regtype[], 
   col86 reltime, 
   col87 reltime[], 
   col88 serial, 
   col89 smallint, 
   col90 smallint[], 
   col91 smgr, 
   col92 text, 
   col93 text[], 
   col94 tid, 
   col95 tid[], 
   col96 time with time zone, 
   col97 time with time zone[], 
   col98 time without time zone, 
   col99 time without time zone[], 
   col100 timestamp with time zone, 
   col101 timestamp with time zone[], 
   col102 timestamp without time zone, 
   col103 timestamp without time zone[], 
   col104 tinterval, 
   col105 tinterval[], 
   col106 tsquery, 
   col107 tsquery[], 
   col108 tsvector, 
   col109 tsvector[], 
   col110 txid_snapshot, 
   col111 txid_snapshot[], 
   col112 uuid, 
   col113 uuid[], 
   col114 xid, 
   col115 xid[], 
   col116 xml, 
   col117 xml[], 
   CONSTRAINT "Primary key" PRIMARY KEY (col1)
);