//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.21 at 01:32:34 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sa.dk/xmlns/diark/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package dk.sa.xmlns.diark._1_0.tableindex;
