/**
 * The contents of this file are subject to the license and copyright
 * detailed in the LICENSE file at the root of the source
 * tree and available online at
 *
 * https://github.com/keeps/db-preservation-toolkit
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.21 at 01:32:34 PM CEST 
//

package dk.sa.xmlns.diark._1_0_ext.tableindex;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * reference element in siardDiark Archive
 * 
 * <p>
 * Java class for referenceType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="referenceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="column" type="{http://www.sa.dk/xmlns/diark/1.0}SQLIdentifier"/&gt;
 *         &lt;element name="referenced" type="{http://www.sa.dk/xmlns/diark/1.0}SQLIdentifier"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "referenceType", propOrder = {"column", "referenced"})
public class ReferenceType {

  @XmlElement(required = true)
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlSchemaType(name = "token")
  protected String column;
  @XmlElement(required = true)
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlSchemaType(name = "token")
  protected String referenced;

  /**
   * Gets the value of the column property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getColumn() {
    return column;
  }

  /**
   * Sets the value of the column property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setColumn(String value) {
    this.column = value;
  }

  /**
   * Gets the value of the referenced property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getReferenced() {
    return referenced;
  }

  /**
   * Sets the value of the referenced property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setReferenced(String value) {
    this.referenced = value;
  }

}
