//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.24 at 06:16:58 PM WEST 
//


package com.databasepreservation.modules.siard.metadata.jaxb.siard1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.joda.time.DateTime;


/**
 * 
 *           Root element of meta data of the SIARD archive
 *         
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dbname" type="{http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd}mandatoryString"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="archiver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="archiverContact" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dataOwner" type="{http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd}mandatoryString"/>
 *         &lt;element name="dataOriginTimespan" type="{http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd}mandatoryString"/>
 *         &lt;element name="producerApplication" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="archivalDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="messageDigest" type="{http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd}digestType"/>
 *         &lt;element name="clientMachine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="databaseProduct" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="connection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="databaseUser" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="schemas" type="{http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd}schemasType"/>
 *         &lt;element name="users" type="{http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd}usersType"/>
 *         &lt;element name="roles" type="{http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd}rolesType" minOccurs="0"/>
 *         &lt;element name="privileges" type="{http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd}privilegesType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd}versionType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dbname",
    "description",
    "archiver",
    "archiverContact",
    "dataOwner",
    "dataOriginTimespan",
    "producerApplication",
    "archivalDate",
    "messageDigest",
    "clientMachine",
    "databaseProduct",
    "connection",
    "databaseUser",
    "schemas",
    "users",
    "roles",
    "privileges"
})
@XmlRootElement(name = "siardArchive")
public class SiardArchive {

    @XmlElement(required = true)
    protected String dbname;
    protected String description;
    protected String archiver;
    protected String archiverContact;
    @XmlElement(required = true)
    protected String dataOwner;
    @XmlElement(required = true)
    protected String dataOriginTimespan;
    protected String producerApplication;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "date")
    protected DateTime archivalDate;
    @XmlElement(required = true)
    protected String messageDigest;
    protected String clientMachine;
    protected String databaseProduct;
    protected String connection;
    protected String databaseUser;
    @XmlElement(required = true)
    protected SchemasType schemas;
    @XmlElement(required = true)
    protected UsersType users;
    protected RolesType roles;
    protected PrivilegesType privileges;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the dbname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbname() {
        return dbname;
    }

    /**
     * Sets the value of the dbname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbname(String value) {
        this.dbname = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the archiver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchiver() {
        return archiver;
    }

    /**
     * Sets the value of the archiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchiver(String value) {
        this.archiver = value;
    }

    /**
     * Gets the value of the archiverContact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchiverContact() {
        return archiverContact;
    }

    /**
     * Sets the value of the archiverContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchiverContact(String value) {
        this.archiverContact = value;
    }

    /**
     * Gets the value of the dataOwner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataOwner() {
        return dataOwner;
    }

    /**
     * Sets the value of the dataOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataOwner(String value) {
        this.dataOwner = value;
    }

    /**
     * Gets the value of the dataOriginTimespan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataOriginTimespan() {
        return dataOriginTimespan;
    }

    /**
     * Sets the value of the dataOriginTimespan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataOriginTimespan(String value) {
        this.dataOriginTimespan = value;
    }

    /**
     * Gets the value of the producerApplication property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProducerApplication() {
        return producerApplication;
    }

    /**
     * Sets the value of the producerApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProducerApplication(String value) {
        this.producerApplication = value;
    }

    /**
     * Gets the value of the archivalDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public DateTime getArchivalDate() {
        return archivalDate;
    }

    /**
     * Sets the value of the archivalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchivalDate(DateTime value) {
        this.archivalDate = value;
    }

    /**
     * Gets the value of the messageDigest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageDigest() {
        return messageDigest;
    }

    /**
     * Sets the value of the messageDigest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageDigest(String value) {
        this.messageDigest = value;
    }

    /**
     * Gets the value of the clientMachine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientMachine() {
        return clientMachine;
    }

    /**
     * Sets the value of the clientMachine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientMachine(String value) {
        this.clientMachine = value;
    }

    /**
     * Gets the value of the databaseProduct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatabaseProduct() {
        return databaseProduct;
    }

    /**
     * Sets the value of the databaseProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatabaseProduct(String value) {
        this.databaseProduct = value;
    }

    /**
     * Gets the value of the connection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnection() {
        return connection;
    }

    /**
     * Sets the value of the connection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnection(String value) {
        this.connection = value;
    }

    /**
     * Gets the value of the databaseUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatabaseUser() {
        return databaseUser;
    }

    /**
     * Sets the value of the databaseUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatabaseUser(String value) {
        this.databaseUser = value;
    }

    /**
     * Gets the value of the schemas property.
     * 
     * @return
     *     possible object is
     *     {@link SchemasType }
     *     
     */
    public SchemasType getSchemas() {
        return schemas;
    }

    /**
     * Sets the value of the schemas property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchemasType }
     *     
     */
    public void setSchemas(SchemasType value) {
        this.schemas = value;
    }

    /**
     * Gets the value of the users property.
     * 
     * @return
     *     possible object is
     *     {@link UsersType }
     *     
     */
    public UsersType getUsers() {
        return users;
    }

    /**
     * Sets the value of the users property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsersType }
     *     
     */
    public void setUsers(UsersType value) {
        this.users = value;
    }

    /**
     * Gets the value of the roles property.
     * 
     * @return
     *     possible object is
     *     {@link RolesType }
     *     
     */
    public RolesType getRoles() {
        return roles;
    }

    /**
     * Sets the value of the roles property.
     * 
     * @param value
     *     allowed object is
     *     {@link RolesType }
     *     
     */
    public void setRoles(RolesType value) {
        this.roles = value;
    }

    /**
     * Gets the value of the privileges property.
     * 
     * @return
     *     possible object is
     *     {@link PrivilegesType }
     *     
     */
    public PrivilegesType getPrivileges() {
        return privileges;
    }

    /**
     * Sets the value of the privileges property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrivilegesType }
     *     
     */
    public void setPrivileges(PrivilegesType value) {
        this.privileges = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
