//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.24 at 06:16:58 PM WEST 
//

package com.databasepreservation.modules.siard.common.jaxb.siard1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

/**
 * List of candidate key (unique) constraints
 * <p>
 * <p>
 * <p>Java class for candidateKeysType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="candidateKeysType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="candidateKey" type="{http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd}candidateKeyType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD) @XmlType(name = "candidateKeysType", propOrder = {
  "candidateKey"}) public class CandidateKeysType {

        @XmlElement(required = true) protected List<CandidateKeyType> candidateKey;

        /**
         * Gets the value of the candidateKey property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the candidateKey property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCandidateKey().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CandidateKeyType }
         */
        public List<CandidateKeyType> getCandidateKey() {
                if (candidateKey == null) {
                        candidateKey = new ArrayList<CandidateKeyType>();
                }
                return this.candidateKey;
        }

}
