//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.24 at 06:16:58 PM WEST 
//

package com.databasepreservation.modules.siard.common.jaxb.siard1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Column element in siardArchive
 * <p>
 * <p>
 * <p>Java class for columnType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="columnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="folder" type="{http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd}fsName" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="typeOriginal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="defaultValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nullable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD) @XmlType(name = "columnType", propOrder = {"name", "folder", "type",
  "typeOriginal", "defaultValue", "nullable", "description"}) public class ColumnType {

        @XmlElement(required = true) protected String name;
        protected String folder;
        @XmlElement(required = true) protected String type;
        protected String typeOriginal;
        protected String defaultValue;
        protected boolean nullable;
        protected String description;

        /**
         * Gets the value of the name property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getName() {
                return name;
        }

        /**
         * Sets the value of the name property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setName(String value) {
                this.name = value;
        }

        /**
         * Gets the value of the folder property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getFolder() {
                return folder;
        }

        /**
         * Sets the value of the folder property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setFolder(String value) {
                this.folder = value;
        }

        /**
         * Gets the value of the type property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getType() {
                return type;
        }

        /**
         * Sets the value of the type property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setType(String value) {
                this.type = value;
        }

        /**
         * Gets the value of the typeOriginal property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getTypeOriginal() {
                return typeOriginal;
        }

        /**
         * Sets the value of the typeOriginal property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setTypeOriginal(String value) {
                this.typeOriginal = value;
        }

        /**
         * Gets the value of the defaultValue property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getDefaultValue() {
                return defaultValue;
        }

        /**
         * Sets the value of the defaultValue property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setDefaultValue(String value) {
                this.defaultValue = value;
        }

        /**
         * Gets the value of the nullable property.
         */
        public boolean isNullable() {
                return nullable;
        }

        /**
         * Sets the value of the nullable property.
         */
        public void setNullable(boolean value) {
                this.nullable = value;
        }

        /**
         * Gets the value of the description property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getDescription() {
                return description;
        }

        /**
         * Sets the value of the description property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setDescription(String value) {
                this.description = value;
        }

}
